name: Armisticefilms.com
favicon: null
layout_spectrum: 0.24506
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#5b574b'
    - '#ffffff'
    - '#a9a18c'
    - '#d50100'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
