typography_spectrum: 0.9899249188601971
color:
  brandStrength: 0.5681262142024934
  lightness: 0.2949699789751321
  saturation: 0.4230611470993608
  rhythmicContrast: 0.6713368813507259
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.16454485640861094
analytics:
  twitter: null
  google: UA-83045337-1
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d52e9dc0-4c5b-4e99-a4a8-357eed594450.png
name: Armisticefilms.com
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: Armistice Films on Facebook
    url: 'https://www.facebook.com/ArmisticeFilms/'
    type: external
  - name: Enemy Aliens The Movie on Facebook
    url: 'https://www.facebook.com/EnemyAliensTheMovie/'
    type: external
  - name: Enemy Aliens on Twitter
    url: 'https://twitter.com/EnemyAliensFilm'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d9ff7e1-8609-497b-8bce-a1e65e546bc7.png
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
