name: Armisticefilms.com
favicon: null
layout_spectrum: 0.8701557673048228
typography_spectrum: 0.7934599760919809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.2696542714256793
  lightness: 0.06766458507627249
  saturation: 0.9383963188156486
  rhythmicContrast: 0.10033925995230675
purpose: []
