typography_spectrum: 0.7934599760919809
color:
  brandStrength: 0.2696542714256793
  lightness: 0
  saturation: 0.9383963
  rhythmicContrast: 0.3553191
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8701557673048228
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/56cdac76-8f78-431a-bfda-0234e351be40.png
name: Armisticefilms.com
cta:
  version: null
  bucket: null
  domain: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Armistice Films
purpose: []
