typography_spectrum: 0.9899249188601971
color:
  brandStrength: 0.5681262142024934
  lightness: 0.2949699789751321
  saturation: 0.4230611470993608
  rhythmicContrast: 0.6713368813507259
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.16454485640861094
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/56cdac76-8f78-431a-bfda-0234e351be40.png
name: Armisticefilms.com
cta:
  version: null
  bucket: null
  domain: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
